Repository SMU-25/frontend, pull requests merged in 2025-07, with the labels that each got.

#24 ✨ [Feat] 발열 리포트 생성 및 리포트 결과 UI 구현
  asset/img/symptoms/0.png
  asset/img/symptoms/1.png
  asset/img/symptoms/10.png
  asset/img/symptoms/2.png
  asset/img/symptoms/3.png
  asset/img/symptoms/4.png
  asset/img/symptoms/5.png
  asset/img/symptoms/6.png
  asset/img/symptoms/7.png
  asset/img/symptoms/8.png
  asset/img/symptoms/9.png
  lib/common/component/navigation_button.dart
  lib/common/component/temperature_chart_widget.dart
  lib/main.dart
  lib/report/component/custom_text_input.dart
  lib/report/view/create_report.dart
  lib/report/view/result_report.dart
  lib/report/view/symptom_summary_dialog.dart
  pubspec.lock
  pubspec.yaml
Labels: ✨ Feature, 🐞 BugFix, 🔨 Refactor

#25 ✨ [Feat] 캘린더 기본 레이아웃 UI 및 캘린더 일정 추가, 삭제 등 일정 관련 UI 구현
  lib/calendar/component/calendar.dart
  lib/calendar/component/custom_text_input.dart
  lib/calendar/component/plan_add.dart
  lib/calendar/component/plan_banner.dart
  lib/calendar/component/plan_card.dart
  lib/calendar/model/plan.dart
  lib/calendar/view/calendar_screen.dart
  lib/common/view/root_tab.dart
  lib/main.dart
  pubspec.lock
  pubspec.yaml
Labels: ✨ Feature, 🔨 Refactor

#27 [Refator] 로그인 화면 UI 오류 수정, 사용되지 않는 import 제거
  .gitignore
  ios/Flutter/Debug.xcconfig
  ios/Flutter/Release.xcconfig
  ios/Podfile
  lib/common/component/login_text_button.dart
  lib/common/component/navigation_button.dart
  lib/common/component/social_login_button.dart
  lib/login/view/login.dart
  lib/mypage/view/add_profile_screen.dart
  pubspec.lock
Labels: 🐞 BugFix, 🔨 Refactor

#29 [Feat] 회원가입, 아이디 찾기, 비밀번호 재설정 화면 UI 구현
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner.xcworkspace/contents.xcworkspacedata
  lib/common/component/custom_input.dart
  lib/common/component/navigation_button.dart
  lib/common/model/user.dart
  lib/login/view/component/find_form_section.dart
  lib/login/view/find_id.dart
  lib/login/view/find_password.dart
  lib/login/view/login.dart
  lib/signup/component/gender_choicechip.dart
  lib/signup/component/input_with_textbutton.dart
  lib/signup/component/small_check.dart
  lib/signup/view/signup_agreement.dart
  lib/signup/view/signup_complete.dart
  lib/signup/view/signup_email.dart
  lib/signup/view/signup_password.dart
  lib/signup/view/signup_user_info.dart
Labels: ✨ Feature

#32 ✨ [Feat] 마이페이지 아이 관련 API 일부 연결 및 리포트 메인페이지 UI 구현
  lib/calendar/view/calendar_screen.dart
  lib/main.dart
  lib/mypage/models/profile_info.dart
  lib/mypage/view/add_profile_symptoms_screen.dart
  lib/mypage/view/edit_baby_profile.dart
  lib/mypage/view/my_screen.dart
  lib/report/component/report_card.dart
  lib/report/model/report_info.dart
  lib/report/view/change_report.dart
  lib/report/view/report.dart
  lib/report/view/result_report.dart
  lib/report/view/symptom_summary_dialog.dart
  pubspec.lock
  pubspec.yaml
Labels: ✨ Feature, 🔨 Refactor, 📬 API

#34 [Feat] 홈, 알림 화면 UI 구현
  asset/img/homecam_mock_data/mock.png
  lib/common/model/baby.dart
  lib/common/view/root_tab.dart
  lib/home/component/body_temperature_card.dart
  lib/home/component/environment_card.dart
  lib/home/component/fever_report_card.dart
  lib/home/component/home_header.dart
  lib/home/component/main_info_card.dart
  lib/home/component/subscribe_card.dart
  lib/home/model/alert.dart
  lib/home/view/alert.dart
  lib/home/view/body_temperature_graph.dart
  lib/home/view/home.dart
  lib/home/view/room_teperature_humidity_graph.dart
  lib/homecam/component/home_cam_form.dart
  lib/homecam/component/home_cam_view.dart
  lib/homecam/component/no_home_cam_view.dart
  lib/homecam/model/home_cam.dart
  lib/homecam/view/create_home_cam.dart
  lib/homecam/view/create_home_cam_complete.dart
  lib/homecam/view/delete_home_cam.dart
  lib/homecam/view/home_cam.dart
  lib/homecam/view/home_cam_list.dart
  lib/homecam/view/update_home_cam.dart
  lib/main.dart
  pubspec.lock
  pubspec.yaml
Labels: ✨ Feature

#37 🖊️ [Refactor] CustomNavigationBar 체온, 온습도 그래프 페이지에 추가
  lib/home/view/body_temperature_graph.dart
  lib/home/view/room_teperature_humidity_graph.dart
Labels: 🔨 Refactor

#39 🖊️ [Refactor] HomeCam UI 라우팅 제대로 수정, HomePage에서 HomCamPage갈 때 pixel 깨지는 거 수정
  lib/common/view/root_tab.dart
  lib/home/view/home.dart
  lib/homecam/view/delete_home_cam.dart
  lib/homecam/view/home_cam.dart
  lib/homecam/view/home_cam_list.dart
  lib/homecam/view/update_home_cam.dart
  lib/main.dart
  pubspec.lock
Labels: ✨ Feature, 🔨 Refactor

#41 🖊️ [Refactor] 아이디 찾기 페이지 삭제, 로그인 API 연결 Init
  lib/common/utils/secure_storage_service.dart
  lib/homecam/view/delete_home_cam.dart
  lib/login/view/find_id.dart
  lib/login/view/login.dart
  lib/main.dart
  pubspec.yaml
Labels: ✨ Feature, 🔨 Refactor

#48 ✨ [Feat] 마이페이지 부모(회원) 관련 API 연결 및 UI 적용
  lib/main.dart
  lib/mypage/component/email_input.dart
  lib/mypage/models/guardian_profile.dart
  lib/mypage/view/add_profile_symptoms_screen.dart
  lib/mypage/view/edit_baby_profile.dart
  lib/mypage/view/edit_my_profile.dart
  lib/mypage/view/my_screen.dart
  lib/report/model/report_info.dart
  lib/report/view/change_report.dart
  lib/report/view/report.dart
  lib/report/view/result_report.dart
  lib/report/view/symptom_summary_dialog.dart
  lib/settings/view/settings_screen.dart
Labels: ✨ Feature, 🔨 Refactor, 📬 API

#53 [Bugfix] 로그인 후 nav bar 안보이는 문제 해결
  lib/login/view/login.dart
Labels: 🐞 BugFix

#54 🔨 [Refactor] accessToken 처리 개선 및 이미지 처리 기능 추가
  lib/common/component/temperature_chart_widget.dart
  lib/mypage/component/profile_image_with_add_icon.dart
  lib/mypage/view/add_profile_screen.dart
  lib/mypage/view/add_profile_symptoms_screen.dart
  lib/mypage/view/edit_baby_profile.dart
  lib/mypage/view/edit_my_profile.dart
  lib/mypage/view/my_screen.dart
  lib/report/view/change_report.dart
  lib/report/view/report.dart
  lib/report/view/result_report.dart
  lib/report/view/symptom_summary_dialog.dart
  lib/settings/component/custom_appbar.dart
  lib/settings/view/settings_screen.dart
  pubspec.lock
  pubspec.yaml
Labels: ✨ Feature, 🔨 Refactor, 📬 API
